name: Dependency Review

on:
  pull_request:

permissions:
  contents: read

jobs:
  osv-scan:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/google/osv-scanner:latest
    steps:
      - uses: actions/checkout@v7
      - run: /osv-scanner scan source --recursive .
